export const GET_ERRORS = "GET_ERRORS";

export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND";
export const CLEAR_CURRENT_PRODUCT = "PRODUCT_NOT_FOUND";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const PERSON_LOADING = "PERSON_LOADING";
export const PERSON_NOT_FOUND = "PERSON_NOT_FOUND";
export const CLEAR_CURRENT_PERSON = "PERSON_NOT_FOUND";
export const GET_PERSON = "GET_PERSON";
export const GET_PERSONS = "GET_PERSONS";
export const DELETE_PERSON = "DELETE_PERSON";
export const ADD_PERSON = "ADD_PERSON";
export const UPDATE_PERSON = "UPDATE_PERSON";

export const IDENTITY_LOADING = "IDENTITY_LOADING";
export const IDENTITY_NOT_FOUND = "IDENTITY_NOT_FOUND";
export const CLEAR_CURRENT_IDENTITY = "IDENTITY_NOT_FOUND";
export const GET_IDENTITY = "GET_IDENTITY";
export const GET_IDENTITIES = "GET_IDENTITIES";
export const DELETE_IDENTITY = "DELETE_IDENTITY";
export const ADD_IDENTITY = "ADD_IDENTITY";
export const UPDATE_IDENTITY = "UPDATE_IDENTITY";

export const COMPANY_LOADING = "COMPANY_LOADING";
export const COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND";
export const CLEAR_CURRENT_COMPANY = "COMPANY_NOT_FOUND";
export const GET_COMPANY = "GET_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const ADD_COMPANY = "ADD_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";

export const MARKETSECTOR_LOADING = "MARKETSECTOR_LOADING";
export const MARKETSECTOR_NOT_FOUND = "MARKETSECTOR_NOT_FOUND";
export const CLEAR_CURRENT_MARKETSECTOR = "MARKETSECTOR_NOT_FOUND";
export const GET_MARKETSECTOR = "GET_MARKETSECTOR";
export const GET_MARKETSECTORS = "GET_MARKETSECTORS";
export const DELETE_MARKETSECTOR = "DELETE_MARKETSECTOR";
export const ADD_MARKETSECTOR = "ADD_MARKETSECTOR";
export const UPDATE_MARKETSECTOR = "UPDATE_MARKETSECTOR";

export const OFFICESECTOR_LOADING = "OFFICESECTOR_LOADING";
export const OFFICESECTOR_NOT_FOUND = "OFFICESECTOR_NOT_FOUND";
export const CLEAR_CURRENT_OFFICESECTOR = "OFFICESECTOR_NOT_FOUND";
export const GET_OFFICESECTOR = "GET_OFFICESECTOR";
export const GET_OFFICESECTORS = "GET_OFFICESECTORS";
export const DELETE_OFFICESECTOR = "DELETE_OFFICESECTOR";
export const ADD_OFFICESECTOR = "ADD_OFFICESECTOR";
export const UPDATE_OFFICESECTOR = "UPDATE_OFFICESECTOR";

export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND";
export const CLEAR_CURRENT_CATEGORY = "CATEGORY_NOT_FOUND";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
