export const GET_ERRORS = "GET_ERRORS";

export const SETTING_LOADING = "SETTING_LOADING";
export const SETTING_NOT_FOUND = "SETTING_NOT_FOUND";
export const CLEAR_CURRENT_SETTING = "SETTING_NOT_FOUND";
export const GET_SETTING = "GET_SETTING";
export const GET_SETTINGS = "GET_SETTINGS";
export const DELETE_SETTING = "DELETE_SETTING";
export const ADD_SETTING = "ADD_SETTING";
export const UPDATE_SETTING = "UPDATE_SETTING";

export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND";
export const CLEAR_CURRENT_PRODUCT = "PRODUCT_NOT_FOUND";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_DIVERSITY_PRODUCT = "ADD_DIVERSITY_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const PERSON_LOADING = "PERSON_LOADING";
export const PERSON_NOT_FOUND = "PERSON_NOT_FOUND";
export const CLEAR_CURRENT_PERSON = "PERSON_NOT_FOUND";
export const GET_PERSON = "GET_PERSON";
export const GET_PERSONS = "GET_PERSONS";
export const DELETE_PERSON = "DELETE_PERSON";
export const ADD_PERSON = "ADD_PERSON";
export const UPDATE_PERSON = "UPDATE_PERSON";

export const IDENTITY_LOADING = "IDENTITY_LOADING";
export const IDENTITY_NOT_FOUND = "IDENTITY_NOT_FOUND";
export const CLEAR_CURRENT_IDENTITY = "IDENTITY_NOT_FOUND";
export const GET_IDENTITY = "GET_IDENTITY";
export const GET_IDENTITIES = "GET_IDENTITIES";
export const DELETE_IDENTITY = "DELETE_IDENTITY";
export const ADD_IDENTITY = "ADD_IDENTITY";
export const UPDATE_IDENTITY = "UPDATE_IDENTITY";

export const COMPANY_LOADING = "COMPANY_LOADING";
export const COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND";
export const CLEAR_CURRENT_COMPANY = "COMPANY_NOT_FOUND";
export const GET_COMPANY = "GET_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const ADD_COMPANY = "ADD_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";

export const MARKETSECTOR_LOADING = "MARKETSECTOR_LOADING";
export const MARKETSECTOR_NOT_FOUND = "MARKETSECTOR_NOT_FOUND";
export const CLEAR_CURRENT_MARKETSECTOR = "MARKETSECTOR_NOT_FOUND";
export const GET_MARKETSECTOR = "GET_MARKETSECTOR";
export const GET_MARKETSECTORS = "GET_MARKETSECTORS";
export const DELETE_MARKETSECTOR = "DELETE_MARKETSECTOR";
export const ADD_MARKETSECTOR = "ADD_MARKETSECTOR";
export const UPDATE_MARKETSECTOR = "UPDATE_MARKETSECTOR";

export const OFFICESECTOR_LOADING = "OFFICESECTOR_LOADING";
export const OFFICESECTOR_NOT_FOUND = "OFFICESECTOR_NOT_FOUND";
export const CLEAR_CURRENT_OFFICESECTOR = "OFFICESECTOR_NOT_FOUND";
export const GET_OFFICESECTOR = "GET_OFFICESECTOR";
export const GET_OFFICESECTORS = "GET_OFFICESECTORS";
export const DELETE_OFFICESECTOR = "DELETE_OFFICESECTOR";
export const ADD_OFFICESECTOR = "ADD_OFFICESECTOR";
export const UPDATE_OFFICESECTOR = "UPDATE_OFFICESECTOR";

export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND";
export const CLEAR_CURRENT_CATEGORY = "CATEGORY_NOT_FOUND";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const SUBCATEGORY_LOADING = "SUBCATEGORY_LOADING";
export const SUBCATEGORY_NOT_FOUND = "SUBCATEGORY_NOT_FOUND";
export const CLEAR_CURRENT_SUBCATEGORY = "SUBCATEGORY_NOT_FOUND";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY";
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY";

export const GROUP_LOADING = "GROUP_LOADING";
export const GROUP_NOT_FOUND = "GROUP_NOT_FOUND";
export const CLEAR_CURRENT_GROUP = "GROUP_NOT_FOUND";
export const GET_GROUP = "GET_GROUP";
export const GET_GROUPS = "GET_GROUPS";
export const DELETE_GROUP = "DELETE_GROUP";
export const ADD_GROUP = "ADD_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";

export const COLOR_LOADING = "COLOR_LOADING";
export const COLOR_NOT_FOUND = "COLOR_NOT_FOUND";
export const CLEAR_CURRENT_COLOR = "COLOR_NOT_FOUND";
export const GET_COLOR = "GET_COLOR";
export const GET_COLORS = "GET_COLORS";
export const DELETE_COLOR = "DELETE_COLOR";
export const ADD_COLOR = "ADD_COLOR";
export const UPDATE_COLOR = "UPDATE_COLOR";

export const MATERIAL_LOADING = "MATERIAL_LOADING";
export const MATERIAL_NOT_FOUND = "MATERIAL_NOT_FOUND";
export const CLEAR_CURRENT_MATERIAL = "MATERIAL_NOT_FOUND";
export const GET_MATERIAL = "GET_MATERIAL";
export const GET_MATERIALS = "GET_MATERIALS";
export const DELETE_MATERIAL = "DELETE_MATERIAL";
export const ADD_MATERIAL = "ADD_MATERIAL";
export const UPDATE_MATERIAL = "UPDATE_MATERIAL";

export const SUPPLIER_LOADING = "SUPPLIER_LOADING";
export const SUPPLIER_NOT_FOUND = "SUPPLIER_NOT_FOUND";
export const CLEAR_CURRENT_SUPPLIER = "SUPPLIER_NOT_FOUND";
export const GET_SUPPLIER = "GET_SUPPLIER";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
