export const GET_ERRORS = "GET_ERRORS";

export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND";
export const CLEAR_CURRENT_PRODUCT = "PRODUCT_NOT_FOUND";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";

export const PERSON_LOADING = "PERSON_LOADING";
export const PERSON_NOT_FOUND = "PERSON_NOT_FOUND";
export const CLEAR_CURRENT_PERSON = "PERSON_NOT_FOUND";
export const GET_PERSON = "GET_PERSON";
export const GET_PERSONS = "GET_PERSONS";
export const DELETE_PERSON = "DELETE_PERSON";
export const ADD_PERSON = "ADD_PERSON";
